services:
  fess01:
    image: ghcr.io/codelibs/fess:14.19.2
    # build: ./playwright # use Playwright
    container_name: fess01
    environment:
      - "SEARCH_ENGINE_HTTP_URL=http://search01:9200"
      - "FESS_DICTIONARY_PATH=${FESS_DICTIONARY_PATH:-/usr/share/opensearch/config/dictionary/}"
      - "FESS_PLUGINS=fess-webapp-semantic-search:14.19.2 fess-ds-wikipedia:14.19.2"
      # - "FESS_PLUGINS=fess-webapp-semantic-search:14.19.2"
    ports:
      # - "8080:8080"
      - "8081:8080"
    networks:
      - search_net
    depends_on:
      - search01
      # - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    volumes:
      - /Users/shoichirosato/Documents:/var/www
      # - ./conf/fess/system.properties:/usr/share/fess/config/system.properties
      - ./fess/conf/system.properties:/usr/share/fess/app/WEB-INF/conf/system.properties

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8082:80"
  #   volumes:
  #     - /Users/shoichirosato/Documents:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - search_net
  #   restart: unless-stopped

networks:
  search_net:
    driver: bridge
